// Generated by scripts/deploy_frontend_proxy.py - public identifiers only, no secret.
window.NOVAMART_CONFIG = {
  "region": "us-east-1",
  "userPoolId": "us-east-1_a6uxoeZ9O",
  "clientId": "1srmdfb81656sojo3agtbgg6mg",
  "apiUrl": "https://5mdfgxxsvvmo5g6i7pgf3f3g6i0wiwcb.lambda-url.us-east-1.on.aws/"
};
